# Generated by Django 5.2.17 on 2026-08-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='地点')),
                ('taken_on', models.CharField(blank=True, max_length=64, verbose_name='拍摄时间文案')),
                ('image_url', models.URLField(verbose_name='图片地址')),
                ('aspect', models.CharField(choices=[('landscape', '横图'), ('portrait', '竖图')], default='landscape', max_length=16, verbose_name='比例')),
                ('category', models.CharField(db_index=True, max_length=32, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('published', models.BooleanField(default=True, verbose_name='已发布')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
