# Generated by Django 5.2.17 on 2026-08-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role_bio_avatar_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=128, verbose_name='头衔/副标题')),
                ('quote', models.TextField(blank=True, verbose_name='引言')),
                ('body', models.TextField(blank=True, help_text='多段用空行分隔', verbose_name='正文')),
                ('focus_tags', models.JSONField(blank=True, default=list, verbose_name='关注标签')),
                ('stats', models.JSONField(blank=True, default=list, verbose_name='数据卡片')),
                ('timeline', models.JSONField(blank=True, default=list, verbose_name='时间线')),
                ('timeline_subtitle', models.CharField(blank=True, max_length=128, verbose_name='时间线副标题')),
                ('influences', models.JSONField(blank=True, default=list, verbose_name='影响与资源')),
                ('tech_stack', models.JSONField(blank=True, default=list, verbose_name='技术栈')),
                ('stack_note', models.TextField(blank=True, verbose_name='技术栈备注')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '关于页配置',
                'verbose_name_plural': '关于页配置',
            },
        ),
    ]
